export const FETCH_DATA_TIME_LINE = 'FETCH_DATA_TIME_LINE';
export const FETCH_DATA_TIME_LINE_SUCCESS = 'FETCH_DATA_TIME_LINE_SUCCESS';
export const FETCH_DATA_TIME_LINE_FAIL = 'FETCH_DATA_TIME_LINE_FAIL';
export const ON_LIKE_CLICK = 'ON_LIKE_CLICK';
export const SHOW_INFO_CARD = 'SHOW_INFO_CARD';
export const HIDE_INFO_CARD = 'HIDE_INFO_CARD';