export const FETCH_DATA_TRENDING = 'FETCH_DATA_TRENDING';
export const FETCH_DATA_TRENDING_SUCCESS = 'FETCH_DATA_TRENDING_SUCCESS';
export const FETCH_DATA_TRENDING_FAIL = 'FETCH_DATA_TRENDING_FAIL';
export const FETCH_DATA_TRENDING_MORE = 'FETCH_DATA_TRENDING_MORE';