export const FETCH_DATA_FOLLOW = 'FETCH_DATA_FOLLOW';
export const FETCH_DATA_FOLLOW_SUCCESS = 'FETCH_DATA_FOLLOW_SUCCESS';
export const FETCH_DATA_FOLLOW_FAIL = 'FETCH_DATA_FOLLOW_FAIL';
export const FETCH_DATA_FOLLOW_MORE = 'FETCH_DATA_FOLLOW_MORE';
export const SHOW_CARD = 'SHOW_CARD';
export const HIDE_CARD = 'HIDE_CARD';
export const ON_FOLLOW = 'ON_FOLLOW';